Jobby/Models/UserSkill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobby.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Jobby.Models.Extended;

    [MetadataType(typeof(UserSkillMetadata))]
    public partial class UserSkill
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string SkillName { get; set; }
        public byte SkillLevel { get; set; }
        public bool IsLanguage { get; set; }
    
        public virtual User User { get; set; }
    }
}

Jobby/Controllers/EmployeeProfileController.cs
using Jobby.Models;
using Jobby.Models.Extended;
using Jobby.Utilities;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Jobby.Controllers
{
    [Authorize]
    public class EmployeeProfileController : Controller
    {
        private JobbyEntities db = new JobbyEntities();

        public ActionResult Index()
        {
            string controller = SecurityUtilities.GetAuthenticatedUserType();
            if (controller != "Employee")
            {
                //redirect to home if request isn't from employee
                return RedirectToAction("Index", controller);
            }
            Guid id = SecurityUtilities.GetAuthenticatedUserID();
            var user = db.Users.Where(u => u.ID == id).FirstOrDefault();
            return View(user);
        }

        public ActionResult PersonalInformation() 
        {
            Guid id = SecurityUtilities.GetAuthenticatedUserID();
            var user = db.Users.Where(u => u.ID == id).FirstOrDefault();
            var employee = db.Employees.Where(emp => emp.UserID == id).FirstOrDefault();
            PersonalInfoViewModel PersonalInfoVM = new PersonalInfoViewModel() {
            FName=user.FName,
            LName=user.LName,
            CountryID=employee.CountryID,
            City=employee.City,
            PhoneNumber = employee.PhoneNumber,
            BirthDate=employee.BirthDate,
            MartialStatus=employee.MartialStatus,
            MilitaryStatus=employee.MilitaryStatus
            };
            ViewBag.CountryID = new SelectList(db.Countries, "Id", "Name", employee.CountryID);
            return View(PersonalInfoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalInformation(PersonalInfoViewModel PersonalInformationVM)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        Guid id = SecurityUtilities.GetAuthenticatedUserID();
                        var user = db.Users.Where(u => u.ID == id).FirstOrDefault();
                        user.FName = PersonalInformationVM.FName;
                        user.LName = PersonalInformationVM.LName;
                        db.SaveChanges();

                        var employee = db.Employees.Where(emp => emp.UserID == id).FirstOrDefault();
                        employee.CountryID = PersonalInformationVM.CountryID;
                        employee.City = PersonalInformationVM.City;
                        employee.PhoneNumber = PersonalInformationVM.PhoneNumber;
                        employee.BirthDate = PersonalInformationVM.BirthDate;
                        employee.MartialStatus = PersonalInformationVM.MartialStatus;
                        employee.MilitaryStatus = PersonalInformationVM.MilitaryStatus;
                        db.SaveChanges();

                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch (Exception) 
                    {
                        ModelState.AddModelError("SaveFaild", "Save changes faild.");
                        transaction.Rollback();
                        ViewBag.CountryID = new SelectList(db.Countries, "Id", "Name", PersonalInformationVM.CountryID);
                        return View(PersonalInformationVM);
                    }
                }
            }
            // if we got here , an error occured
            ViewBag.CountryID = new SelectList(db.Countries, "Id", "Name", PersonalInformationVM.CountryID);
            return View(PersonalInformationVM);
        }

        public ActionResult EducationInformation()
        {
            Guid id = SecurityUtilities.GetAuthenticatedUserID();
            var userEducation = db.UserEducations.Where(u => u.UserID == id).FirstOrDefault();
            return View(userEducation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EducationInformation([Bind(Include ="Degree,Entity,Field,Grade,StartYear,EndYear")]UserEducation userEducation)
        {
            if (ModelState.IsValid)
            {
                Guid id = SecurityUtilities.GetAuthenticatedUserID();
                userEducation.UserID = id;
                var result = db.UserEducations.Where(u => u.UserID == id).FirstOrDefault();
                if (result == null)
                {
                    db.UserEducations.Add(userEducation);
                    db.SaveChanges();
                }
                else 
                {
                    result.UserID = userEducation.UserID;
                    result.StartYear = userEducation.StartYear;
                    result.EndYear = userEducation.EndYear;
                    result.Degree = userEducation.Degree;
                    result.Field = userEducation.Field;
                    result.Entity = userEducation.Entity;
                    result.Grade = userEducation.Grade;
                    db.Entry(result).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            // if we got here , an error occured
            return View(userEducation);
        }

        public ActionResult WorkInformation()
        {
            Guid id = SecurityUtilities.GetAuthenticatedUserID();
            var employee = db.Employees.Where(emp => emp.UserID == id).FirstOrDefault();
            ViewBag.CvExist = (employee.CV != null) ? true : false;
            WorkInfoViewModel WorkInfoVM = new WorkInfoViewModel() {
                Salary = employee.Salary,
                JobStatus = employee.JobStatus,
                CareerLevel = employee.CareerLevel,
            };
            return View(WorkInfoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WorkInformation(WorkInfoViewModel WorkInfoVM)
        {
            if (ModelState.IsValid)
            {
                Guid id = SecurityUtilities.GetAuthenticatedUserID();
                var employee = db.Employees.Where(emp => emp.UserID == id).FirstOrDefault();
                employee.Salary = WorkInfoVM.Salary;
                employee.JobStatus = WorkInfoVM.JobStatus;
                employee.CareerLevel = WorkInfoVM.CareerLevel;
                if (WorkInfoVM.CV != null && WorkInfoVM.CV.ContentLength > 0)
                {
                    // convert cv to array of binary then store it into database
                    Stream stream = WorkInfoVM.CV.InputStream;
                    BinaryReader Br = new BinaryReader(stream);
                    employee.CV = Br.ReadBytes((int)stream.Length);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // if we got here , an error occured
            return View(WorkInfoVM);
        }
        
        public FileResult DownloadCV(Guid? id)
        {
            if (id==null)
            {
                id = SecurityUtilities.GetAuthenticatedUserID();
            }
            var employee = db.Employees.Where(emp => emp.UserID == id).FirstOrDefault();
            return File(employee.CV, "application/pdf", User.Identity.Name + " Cv.pdf");
        }

        public ActionResult SkillsInformation() 
        {
            Guid id = SecurityUtilities.GetAuthenticatedUserID();
            var skills = db.UserSkills.Where(s => s.UserID == id).OrderByDescending(s=>s.SkillLevel);
            if (skills != null) 
            {
                return View(skills.ToList());
            }
            return View();
        }

        public ActionResult AddUserSkill()
        {
            return View("UserSkill");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUserSkill([Bind(Include ="SkillName,SkillLevel,IsLanguage")]UserSkill userSkill)
        {
            if (ModelState.IsValid)
            {
                Guid id = SecurityUtilities.GetAuthenticatedUserID();
                userSkill.UserID = id;
                userSkill.ID = Guid.NewGuid();
                db.UserSkills.Add(userSkill);
                db.SaveChanges();
                return RedirectToAction("SkillsInformation");
            }
            // if we got here , an error occured
            return View("UserSkill",userSkill);
        }

        public ActionResult EditUserSkill(Guid ID)
        {
            var result = db.UserSkills.Where(s => s.ID == ID).FirstOrDefault();
            if (result != null)
            {
                return View("UserSkill",result);
            }
            return RedirectToAction("SkillsInformation");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserSkill([Bind(Include = "ID,UserID,SkillName,SkillLevel,IsLanguage")]UserSkill userSkill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userSkill).State=EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SkillsInformation");
            }
            // if we got here , an error occured
            return View(userSkill);
        }
        
        [HttpPost]
        public PartialViewResult DeleteUserSkill(Guid ID)
        {
            var result = db.UserSkills.Where(s => s.ID == ID).FirstOrDefault();
            db.UserSkills.Remove(result);
            db.SaveChanges();
            var skills = db.UserSkills.Where(s => s.UserID == result.UserID).OrderByDescending(s => s.SkillLevel);
            if (skills != null)
            {
                return PartialView("_SkillsInformation", skills.ToList());
            }
            return PartialView("_SkillsInformation");
        }

Jobby/Views/EmployeeProfile/Index.cshtml
@model Jobby.Models.User
@{ ViewBag.Title = "Profile"; }

@section style
{
    <link rel="stylesheet" href="~/Content/profile.css" />
    <link rel="stylesheet" href="~/Content/employee-profile.css" />
}

@Html.Partial("_EmployeeNavbar")

<div class="container content">
    <div class="row py-4">
        @using (Html.BeginForm("ChangeImg", "User", FormMethod.Post, new { enctype = "multipart/form-data", id = "img-form", @class = "w-100" }))
        {
            <div class="w-100 px-2">
                <input type="file" id="upload" name="upload" class="d-none" accept=".png, .jpg, .jpeg" />
                @if (Model.Img != null)
                {
                    var base64 = Convert.ToBase64String(Model.Img);
                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <a id="upload-img" title="Change Profile Picture" href=@Url.Action("ChangeImg","User")>
                        <img src='@imgsrc' class="img-thumbnail" alt="profile picture" />
                        <i class="fas fa-camera fa-2x"></i>
                    </a>
                }
                else
                {
                    <a id="upload-img" title="Change Profile Picture" href=@Url.Action("ChangeImg","User")>
                        <img src="~/Images/user.png" class="img-thumbnail" alt="profile picture" />
                        <i class="fas fa-camera fa-2x"></i>
                    </a>
                }
            </div>
        }
        <div class="w-100 px-2">
            <h3>Welcome, @Model.FName @Model.LName</h3>
            <p class="mb-3">Manage your personal, education, skills, work and security information to improve your jobby profile.</p>
        </div>
        <div class="container col-md-10">
            <div class="row">
                <div class="col-lg-6 mb-4">
                    <div id="personal">
                        <i class="fas fa-address-card fa-4x"></i>
                        <h3>Personal Information</h3>
                        <p>Change your name, age, mobile number, etc.</p>
                        <a href=@Url.Action("PersonalInformation","EmployeeProfile") class="text-decoration-none">Manage</a>
                    </div>

                </div>
                <div class="col-lg-6 mb-4">
                    <div id="education">
                        <i class="fas fa-graduation-cap fa-4x"></i>
                        <h3>Education Information</h3>
                        <p>Change field(s) of study, certificates, etc.</p>
                        <a href=@Url.Action("EducationInformation","EmployeeProfile") class="text-decoration-none">Manage</a>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div id="skill">
                        <i class="fab fa-stripe-s fa-4x"></i>
                        <h3>Skills Information</h3>
                        <p>Update your languages, personal and technical skills.</p>
                        <a href=@Url.Action("SkillsInformation","EmployeeProfile") class="text-decoration-none">Manage</a>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div id="work">
                        <i class="fas fa-briefcase fa-4x"></i>
                        <h3>Work Information</h3>
                        <p>Updating may increase your chance of obtaining the appropriate job.</p>
                        <a href=@Url.Action("WorkInformation","EmployeeProfile") class="text-decoration-none">Manage</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div id="security">
                        <i class="fas fa-shield-alt fa-4x"></i>
                        <h3>Security Information</h3>
                        <p>Security information helps you protecting your account.</p>
                        <a href=@Url.Action("ChangePassword","User") class="text-decoration-none">Manage</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/profile.js"></script>
}

Jobby/Views/EmployeeProfile/Profile.cshtml
@model Jobby.Models.User
@{ ViewBag.Title = "Employee Profile"; }
@section style
{
    <link rel="stylesheet" href="~/Content/user-profile.css" />
}

@Html.Partial("_EmployerNavbar")

<div class="container content center-vertical px-lg-5">
    <div class="row px-3 px-lg-5">
        <div id="profile-container" class="col-md-8 offset-md-2">
            <div class="w-100" id="profile-picture">
                @if (Model.Img != null)
                {
                    var base64 = Convert.ToBase64String(Model.Img);
                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' class="img-thumbnail" alt="profile picture" />
                }
                else
                {
                    <img src="~/Images/user.png" class="img-thumbnail" alt="profile picture" />
                }
                <h2 class="heavy-text">@Model.FName @Model.LName</h2>
                <div id="accordion" class="text-left">
                    <div class="card mb-2">
                        <div class="card-header">
                            <a class="card-link heavy-text" data-toggle="collapse" href="#personal">
                                Personal Information <i class="fas fa-chevron-down float-right"></i>
                            </a>
                        </div>
                        <div id="personal" class="collapse show" data-parent="#accordion">
                            <div class="card-body">
                                @if (Model.Employee.BirthDate != null)
                                {
                                    var birthdate = @Convert.ToDateTime(Model.Employee.BirthDate);
                                    var age = DateTime.Today.Year - birthdate.Year;
                                    if (birthdate.Date > DateTime.Today.AddYears(-age)) age--;
                                    <p class="m-0"> <span class="heavy-text">Age : </span>@age Years.</p>
                                }
                                @if (Model.Employee.CountryID != null || Model.Employee.City != null)
                                {
                                    if (Model.Employee.CountryID != null && Model.Employee.City != null)
                                    {
                                        <p class="m-0"> <span class="heavy-text">Address : </span>@Model.Employee.Country.Name, @Model.Employee.City.</p>
                                    }
                                    else
                                    {
                                        <p class="m-0"> <span class="heavy-text">Address : </span>@Model.Employee.Country.Name @Model.Employee.City.</p>
                                    }
                                }
                                @if (Model.Employee.PhoneNumber != null)
                                {
                                    <p class="m-0"> <span class="heavy-text">Mobile Number : </span>@Model.Employee.PhoneNumber.</p>
                                }
                                <p class="m-0"> <span class="heavy-text">Email Address : </span>@Model.Email.</p>
                                @if (Model.Employee.MartialStatus != null)
                                {
                                    <p class="m-0"> <span class="heavy-text">Martial Status : </span>@Model.Employee.MartialStatus.</p>
                                }
                                @if (Model.Employee.MilitaryStatus != null)
                                {
                                    <p class="m-0"> <span class="heavy-text">Military Status : </span>@Model.Employee.MilitaryStatus.</p>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="card mb-2">
                        <div class="card-header">
                            <a class="collapsed card-link heavy-text" data-toggle="collapse" href="#education">
                                Education Information <i class="fas fa-chevron-down float-right"></i>
                            </a>
                        </div>
                        <div id="education" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                @if (Model.UserEducation != null)
                                {
                                    <p class="m-0"> <span class="heavy-text">Studied : </span>@Model.UserEducation.Field at @Model.UserEducation.Entity from @Model.UserEducation.StartYear to @Model.UserEducation.EndYear.</p>
                                    <p class="m-0"> <span class="heavy-text">Degree : </span>@Model.UserEducation.Degree.</p>
                                    <p class="m-0"> <span class="heavy-text">Grade : </span>@Model.UserEducation.Grade.</p>
                                }
                                else
                                {
                                    <p class="m-0 heavy-text no-info"><i class="fas fa-exclamation-circle"></i> Sorry, @Model.FName didn't provide this information.</p>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="card mb-2">
                        <div class="card-header">
                            <a class="collapsed card-link heavy-text" data-toggle="collapse" href="#skills">
                                Skills & Languages Information <i class="fas fa-chevron-down float-right"></i>
                            </a>
                        </div>
                        <div id="skills" class="collapse" data-parent="#accordion">
                            <div class="card-body skills-holder">
                                @if (Model.UserSkills.Where(s => s.UserID == Model.ID).Count() > 0)
                                {
                                    foreach (var skill in Model.UserSkills.Where(s => s.UserID == Model.ID && s.IsLanguage == false).OrderByDescending(s => s.SkillLevel))
                                    {
                                        if (skill.SkillLevel == 5)
                                        {
                                            <span class="skill heavy-text bg-success">@skill.SkillName</span>
                                        }
                                        else if (skill.SkillLevel == 4)
                                        {
                                            <span class="skill heavy-text bg-primary">@skill.SkillName</span>
                                        }
                                        else if (skill.SkillLevel == 3)
                                        {
                                            <span class="skill heavy-text bg-warning">@skill.SkillName</span>
                                        }
                                        else
                                        {
                                            <span class="skill heavy-text bg-danger">@skill.SkillName</span>
                                        }
                                    }
                                    <br />
                                    foreach (var skill in Model.UserSkills.Where(s => s.UserID == Model.ID && s.IsLanguage == true).OrderByDescending(s => s.SkillLevel))
                                    {
                                        if (skill.SkillLevel == 5)
                                        {
                                            <span class="skill heavy-text bg-success">@skill.SkillName</span>
                                        }
                                        else if (skill.SkillLevel == 4)
                                        {
                                            <span class="skill heavy-text bg-primary">@skill.SkillName</span>
                                        }
                                        else if (skill.SkillLevel == 3)
                                        {
                                            <span class="skill heavy-text bg-warning">@skill.SkillName</span>
                                        }
                                        else
                                        {
                                            <span class="skill heavy-text bg-danger">@skill.SkillName</span>
                                        }
                                    }
                                }
                                else
                                {
                                    <p class="m-0 heavy-text no-info"><i class="fas fa-exclamation-circle"></i> Sorry, @Model.FName didn't provide this information.</p>
                                }

                            </div>
                        </div>
                    </div>
                    <div class="card mb-2">
                        <div class="card-header">
                            <a class="collapsed card-link heavy-text" data-toggle="collapse" href="#work">
                                Work Information <i class="fas fa-chevron-down float-right"></i>
                            </a>
                        </div>
                        <div id="work" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                @{ bool info_exist = false;}
                                @if (Model.Employee.Salary != null)
                                {
                                    info_exist = true;
                                    <p class="m-0"> <span class="heavy-text">Minimum Salary : </span>@Model.Employee.Salary EGP.</p>
                                }
                                @if (Model.Employee.JobStatus != null)
                                {
                                    info_exist = true;
                                    <p class="m-0"> <span class="heavy-text">Job Status : </span>@Model.Employee.JobStatus.</p>
                                }
                                @if (Model.Employee.CareerLevel != null)
                                {
                                    info_exist = true;
                                    <p class="m-0"> <span class="heavy-text">Career Level : </span>@Model.Employee.CareerLevel.</p>
                                }
                                @if (Model.Employee.CV != null)
                                {
                                    info_exist = true;
                                    <p class="m-0">
                                        <span class="heavy-text">Resume : </span>
                                        <a class="text-decoration-none text-info" href=@Url.Action("DownloadCV","EmployeeProfile",new { id = Model.ID })>Download<i class="fas fa-arrow-circle-down"></i></a>
                                    </p>
                                }
                                @if (!info_exist)
                                {
                                    <p class="m-0 heavy-text no-info"><i class="fas fa-exclamation-circle"></i> Sorry, @Model.FName didn't provide this information.</p>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Jobby/Views/EmployeeProfile/SkillsInformation.cshtml
@model IEnumerable<Jobby.Models.UserSkill>
@{ ViewBag.Title = "Skills Information"; }
@section style
{
    <link rel="stylesheet" href="~/Content/skills-info.css" />
}

@Html.Partial("_EmployeeNavbar")

<div class="container content center-vertical">
    <div class="row" id="user-skills-container">
        @Html.Partial("_SkillsInformation")
    </div>
</div>

Jobby/Views/EmployeeProfile/WorkInformation.cshtml
@model Jobby.Models.Extended.WorkInfoViewModel
@{ ViewBag.Title = "Personal Information"; }

@Html.Partial("_EmployeeNavbar")

<div class="container content center-vertical">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            @using (Html.BeginForm("WorkInformation", "EmployeeProfile", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-8 offset-lg-2 px-3 px-sm-5" id="personal-info-form">
                    <div>
                        <i class="fas fa-briefcase fa-5x"></i>
                        <h2 class="mb-3 text-uppercase heavy-text">Work Information</h2>
                    </div>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" title="Expected Salary"><i class="fas fa-coins"></i></span>
                        </div>
                        @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control", placeholder = "Expected Salary (EGP/Month)", min = "500", step = "100" } })
                    </div>
                    <div class="error-msg">
                        @Html.ValidationMessageFor(model => model.Salary)
                    </div>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" title="Job Status"><i class="fas fa-briefcase"></i></span>
                        </div>
                        @Html.DropDownList("JobStatus",
                        new SelectList(new List<string>() { "Unemployed", "Actively searching", "Not looking for a job" }, Model.JobStatus), "Job Status", new { @class = "custom-select" })
                    </div>
                    <div class="error-msg">
                        @Html.ValidationMessageFor(model => model.JobStatus)
                    </div>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" title="Career Level"><i class="fas fa-layer-group"></i></span>
                        </div>
                        @Html.DropDownList("CareerLevel",
                        new SelectList(new List<string>() { "Volunteer", "Internship", "Student", "Entry Level", "Experienced", "Manager", "Senior Management" }, Model.CareerLevel), "Career Level", new { @class = "custom-select" })
                    </div>
                    <div class="error-msg">
                        @Html.ValidationMessageFor(model => model.CareerLevel)
                    </div>

                    <div class="custom-file">
                        @Html.TextBoxFor(model => model.CV, new { @class = "custom-file-input", type = "file", accept = ".pdf" })
                        <label class="custom-file-label text-left text-secondary" for="customFile">Upload New CV</label>
                    </div>
                    <div class="error-msg text-right">
                        @if (@ViewBag.CvExist)
                        {
                            <a class="text-decoration-none" href=@Url.Action("DownloadCV")>Download Current CV <i class="fas fa-arrow-circle-down"></i></a>
                        }
                    </div>
                    <input type="submit" value="Save Changes" class="btn btn-primary col-12" />
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/work-info.js"></script>
}